export const interaction_values = {
  transition: [
    'all',
    'background',
    'opacity',
    'box-shadow',
    'border',
    'color',
    'width',
    'height',
    'transform',
    'filter',
    'font-size',
  ],
  overflow: ['visible', 'hidden', 'clip', 'scroll', 'auto'],
  overflow_wrap: ['normal', 'break-word', 'anywhere'],
  overscroll_behavior: ['auto', 'contain', 'none'],
  cursor: [
    'auto',
    'default',
    'none',
    'pointer',
    'wait',
    'cell',
    'crosshair',
    'text',
    'vertical-text',
    'move',
    'not-allowed',
    'grab',
    'grabbing',
    'all-scroll',
    'col-resize',
    'row-resize',
    'n-resize',
    'e-resize',
    's-resize',
    'w-resize',
    'ne-resize',
    'nw-resize',
    'se-resize',
    'sw-resize',
    'ew-resize',
    'ns-resize',
    'nesw-resize',
    'nwse-resize',
    'zoom-in',
    'zoom-out',
  ],
  pointer_events: ['auto', 'all', 'none', 'visible', 'painted', 'fill', 'stroke'],
  resize: ['none', 'both', 'horizontal', 'vertical', 'block', 'inline'],
  touch_action: ['none', 'auto', 'pan-x', 'pan-y', 'manipulation', 'pinch-zoom'],
}
